Generate the presigned url when the task launches instead of generati…
farao-community/gridcapa-job-launcher pull request #15
Opened 2023-01-25 13:46 UTC by TheoPascoli

…ng it in database when the file is created

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-02-01 15:47 UTC, schwitzguebel approved these changes

2023-02-01 15:47 UTC, schwitzguebel commented on src/main/resources/application.yml
> +  url: http://localhost:9000
New line at end of file please :)

2023-02-01 15:47 UTC, schwitzguebel commented on src/test/resources/application.yml
> +  url: http://localhost:9000
New line at end of file please :)

2023-02-02 13:36 UTC, schwitzguebel approved these changes

2023-02-03 14:47 UTC, WalAmeni requested changes

2023-02-03 14:47 UTC, WalAmeni commented on pom.xml
> +		<task-manager.version>1.12.0</task-manager.version>
I think we should increment the version of task manager with the new one after release!

2023-02-03 14:47 UTC, WalAmeni commented on src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java
> +                    minioAdapter.generatePreSignedUrlFromFullMinioPath(input.getFileUrl(), 1));
That's working but I don't think it's clean to modify ProcessFileDto here. This is also linked with my comment in the task manager PR, it's not pretty to use the same variable for two different meaning. In the task manager the FileUrl correspond to the object key (Minio path) and here is replaced by an url. I think also it's better to use the minio.generatePresignedUrlFromFullMinioPath method in the process adapter when it creates the process request. We can discuss about it !

2023-02-07 12:39 UTC, closed without merging